data = [

    {'name':'Instagram',
     'follower_count':346,
     'description': 'Social media platform',
     'country': 'United States'},
{'name':'Kunal Shenoy',
     'follower_count':500,
     'description': 'Physical Trainer',
     'country': 'United States'},
{'name':'Haley Schneider',
     'follower_count':440,
     'description': 'Public Health Specialist',
     'country': 'United States'},
{'name':'Cristiano Ronaldo',
     'follower_count':215,
     'description': 'Footballer',
     'country': 'Portugal'},
{'name':'Parker Day',
     'follower_count':36,
     'description': 'Google Ads Specialist',
     'country': 'United States'},
{'name':'Lexi Kennett',
     'follower_count':234,
     'description': 'HR Lead',
     'country': 'United States'},
{'name':'Roger Federer',
     'follower_count':733,
     'description': 'Tennis Player',
     'country': 'Switzerland'},
{'name':'Nikki Minaj',
     'follower_count':553,
     'description': 'Musician',
     'country': 'United States'},
{'name':'Lewis Hamilton',
     'follower_count':563,
     'description': 'Formula One Racer',
     'country': 'United Kingdom'},
{'name':'Gordon Ramsay',
     'follower_count':441,
     'description': 'Chef',
     'country': 'Scotland'},
{'name':'Robert Downey Jr.',
     'follower_count':873,
     'description': 'Actor',
     'country': 'United States'},
{'name':'Mo Salah',
     'follower_count':124,
     'description': 'Footballer',
     'country': 'Egypt'},
{'name':'Khaled',
     'follower_count':211,
     'description': 'Philospher',
     'country': 'Lebanon'},
{'name':'Abby Hansen',
     'follower_count':179,
     'description': 'Day Care Manager',
     'country': 'United States'},
{'name':'Bill Gates',
     'follower_count':664,
     'description': 'Microsoft CEO',
     'country': 'United States'},

]

